### ISSUE TITLE
DO_Robot change detector failing (ShEx)

### ISSUE THREAD

**Issue by andrewsu** [SuLab/GeneWikiCentral#110]
from the [console output](http://jenkins.sulab.org/view/3%20Change%20Detectors/job/DO_Robot/7/console):

```+ python3 run.py
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    from wikidataintegrator.wdi_core import WDItemEngine
  File "/var/lib/jenkins/workspace/DO_Robot/venv/local/lib/python3.6/site-packages/wikidataintegrator-0.2.post0-py3.6.egg/wikidataintegrator/__init__.py", line 3, in <module>
  File "/var/lib/jenkins/workspace/DO_Robot/venv/local/lib/python3.6/site-packages/wikidataintegrator-0.2.post0-py3.6.egg/wikidataintegrator/wdi_core.py", line 16, in <module>
  File "/var/lib/jenkins/workspace/DO_Robot/venv/local/lib/python3.6/site-packages/PyShEx-0.7.3-py3.6.egg/pyshex/__init__.py", line 1, in <module>
  File "/var/lib/jenkins/workspace/DO_Robot/venv/local/lib/python3.6/site-packages/PyShEx-0.7.3-py3.6.egg/pyshex/prefixlib.py", line 4, in <module>
ModuleNotFoundError: No module named 'pyshexc'
Build step 'Execute shell' marked build as failure
Archiving artifacts
No emails were triggered.
Finished: FAILURE
```

Assigning to you, @andrawaag ?

**Comment by andrawaag** [comment]
Still not working

**Comment by andrawaag** [comment]
A change in pyshex initiated this issue. pyshex calls pyshexc, so pyshexc should be included in the requirements or setup.py list of dependencies. However, it is not clear to me yet, where this should be stated, either setup.py or requirements.txt (see https://github.com/SuLab/WikidataIntegrator/issues/88). While testing multiple attempts I noticed that this bot was not using WDI through Pypi, but directly importing it from the master branch. Fixing this turned out to solve this issue. However, the two other issues remain and should be fixed, because next version releases of WDI will introduce this in the Pypi version of WDI. Will, however, close this issue and continue fixing the issue in the respective issues

[x] remove importing Wikidataintegrator from the master branch directly from this bot
[x] Use WDI through Pypi in this bot
[] Fix issue https://github.com/hsolbrig/PyShEx/issues/39
[] Fix issue https://github.com/SuLab/WikidataIntegrator/issues/88
